package android.oldfeel.yanzhuang.item;

import java.io.Serializable;

/**
 * Model class of user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserItem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** userId. */
	private Long userid;

	/** name. */
	private String name;

	/** password. */
	private String password;

	/** email. */
	private String email;

	/** phone. */
	private String phone;

	/** houseNumber. */
	private String housenumber;

	/** birthday. */
	private String birthday;

	/** permission. */
	private Integer permission;

	/** background. */
	private String background;

	/** avatar. */
	private String avatar;

	/** friendMsg. */
	private Boolean friendmsg;

	/** businessMsg. */
	private Boolean businessmsg;

	/** activityMsg. */
	private Boolean activitymsg;

	/** time. */
	private String time;

	private boolean isFollowing;

	private long followingCount;

	private long fansCount;

	private long serverCount;

	private boolean isFans;

	private String lastActivity;
	private String introduction;

	/**
	 * Constructor.
	 */
	public UserItem() {
	}

	public String getIntroduction() {
		return introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	/**
	 * Set the userId.
	 * 
	 * @param userid
	 *            userId
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * Get the userId.
	 * 
	 * @return userId
	 */
	public Long getUserid() {
		return this.userid;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		if (name == null || name.length() == 0) {
			return getEmail();
		}
		return this.name;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the houseNumber.
	 * 
	 * @param housenumber
	 *            houseNumber
	 */
	public void setHousenumber(String housenumber) {
		this.housenumber = housenumber;
	}

	/**
	 * Get the houseNumber.
	 * 
	 * @return houseNumber
	 */
	public String getHousenumber() {
		return this.housenumber;
	}

	/**
	 * Set the birthday.
	 * 
	 * @param birthday
	 *            birthday
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * Get the birthday.
	 * 
	 * @return birthday
	 */
	public String getBirthday() {
		return this.birthday;
	}

	/**
	 * Set the permission.
	 * 
	 * @param permission
	 *            permission
	 */
	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	/**
	 * Get the permission.
	 * 
	 * @return permission
	 */
	public Integer getPermission() {
		return this.permission;
	}

	/**
	 * Set the background.
	 * 
	 * @param background
	 *            background
	 */
	public void setBackground(String background) {
		this.background = background;
	}

	/**
	 * Get the background.
	 * 
	 * @return background
	 */
	public String getBackground() {
		return this.background;
	}

	/**
	 * Set the avatar.
	 * 
	 * @param avatar
	 *            avatar
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * Get the avatar.
	 * 
	 * @return avatar
	 */
	public String getAvatar() {
		return this.avatar;
	}

	/**
	 * Set the friendMsg.
	 * 
	 * @param friendmsg
	 *            friendMsg
	 */
	public void setFriendmsg(Boolean friendmsg) {
		this.friendmsg = friendmsg;
	}

	/**
	 * Get the friendMsg.
	 * 
	 * @return friendMsg
	 */
	public Boolean getFriendmsg() {
		return this.friendmsg;
	}

	/**
	 * Set the businessMsg.
	 * 
	 * @param businessmsg
	 *            businessMsg
	 */
	public void setBusinessmsg(Boolean businessmsg) {
		this.businessmsg = businessmsg;
	}

	/**
	 * Get the businessMsg.
	 * 
	 * @return businessMsg
	 */
	public Boolean getBusinessmsg() {
		return this.businessmsg;
	}

	/**
	 * Set the activityMsg.
	 * 
	 * @param activitymsg
	 *            activityMsg
	 */
	public void setActivitymsg(Boolean activitymsg) {
		this.activitymsg = activitymsg;
	}

	/**
	 * Get the activityMsg.
	 * 
	 * @return activityMsg
	 */
	public Boolean getActivitymsg() {
		return this.activitymsg;
	}

	/**
	 * Set the time.
	 * 
	 * @param time
	 *            time
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * Get the time.
	 * 
	 * @return time
	 */
	public String getTime() {
		return this.time;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserItem other = (UserItem) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}
		return true;
	}

	public boolean isFollowing() {
		return isFollowing;
	}

	public void setFollowing(boolean isFollowing) {
		this.isFollowing = isFollowing;
	}

	public void setFollowingCount(long followingCount) {
		this.followingCount = followingCount;
	}

	public long getFollowingCount() {
		return followingCount;
	}

	public void setFansCount(long fansCount) {
		this.fansCount = fansCount;
	}

	public long getFansCount() {
		return fansCount;
	}

	public void setServerCount(long serverCount) {
		this.serverCount = serverCount;
	}

	public long getServerCount() {
		return serverCount;
	}

	public void setFans(boolean isFans) {
		this.isFans = isFans;
	}

	public boolean isFans() {
		return isFans;
	}

	public void setLastActivity(String lastActivity) {
		this.lastActivity = lastActivity;
	}

	public String getLastActivity() {
		return lastActivity;
	}

}
