package com.yuncommunity.item;

import com.oldfeel.base.BaseItem;

/**
 * Model class of 活动报名.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivitySignUpItem extends BaseItem {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** informationId. */
	private long Informationid;

	/** userId. */
	private long Userid;

	/** name. */
	private String Name;

	/** phone. */
	private String Phone;

	/** email. */
	private String Email;

	/** adultcount. */
	private Integer Adultcount;

	/** childcount. */
	private Integer Childcount;

	/** remark. */
	private String Remark;

	private String Avatar;
	private String Time;

	/**
	 * Constructor.
	 */
	public ActivitySignUpItem() {
	}

	/**
	 * Set the informationId.
	 * 
	 * @param informationid
	 *            informationId
	 */
	public void setInformationid(long informationid) {
		this.Informationid = informationid;
	}

	/**
	 * Get the informationId.
	 * 
	 * @return informationId
	 */
	public long getInformationid() {
		return this.Informationid;
	}

	/**
	 * Set the userId.
	 * 
	 * @param userid
	 *            userId
	 */
	public void setUserid(long userid) {
		this.Userid = userid;
	}

	/**
	 * Get the userId.
	 * 
	 * @return userId
	 */
	public long getUserid() {
		return this.Userid;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.Name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.Name;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.Phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.Phone;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.Email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.Email;
	}

	/**
	 * Set the adultcount.
	 * 
	 * @param adultcount
	 *            adultcount
	 */
	public void setAdultcount(Integer adultcount) {
		this.Adultcount = adultcount;
	}

	/**
	 * Get the adultcount.
	 * 
	 * @return adultcount
	 */
	public Integer getAdultcount() {
		return this.Adultcount;
	}

	/**
	 * Set the childcount.
	 * 
	 * @param childcount
	 *            childcount
	 */
	public void setChildcount(Integer childcount) {
		this.Childcount = childcount;
	}

	/**
	 * Get the childcount.
	 * 
	 * @return childcount
	 */
	public Integer getChildcount() {
		return this.Childcount;
	}

	/**
	 * Set the remark.
	 * 
	 * @param remark
	 *            remark
	 */
	public void setRemark(String remark) {
		this.Remark = remark;
	}

	/**
	 * Get the remark.
	 * 
	 * @return remark
	 */
	public String getRemark() {
		return this.Remark;
	}

	public String getTime() {
		return Time;
	}

	public void setTime(String time) {
		this.Time = time;
	}

	public void setAvatar(String avatar) {
		this.Avatar = avatar;
	}

	public String getAvatar() {
		return Avatar;
	}

}
