package com.yuncommunity.item;

import java.io.Serializable;

/**
 * Model class of user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserItem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** userId. */
	private long Userid;

	/** name. */
	private String Name;

	/** password. */
	private String Password;

	/** email. */
	private String Email;

	/** phone. */
	private String Phone;

	/** houseNumber. */
	private String Housenumber;

	/** birthday. */
	private String Birthday;

	/** permission. */
	private int Permission;

	/** background. */
	private String Background;

	/** avatar. */
	private String Avatar;

	/** friendMsg. */
	private Boolean Friendmsg = true;

	/** businessMsg. */
	private Boolean Businessmsg = true;

	/** activityMsg. */
	private Boolean Activitymsg = true;

	/** time. */
	private String Time;

	private boolean IsFollowing;

	private long FollowingCount;

	private long FansCount;

	private long ServerCount;

	private boolean IsFans;

	private String LastActivity;
	private String Introduction;
	private CommunityItem CommunityInfo;

	public CommunityItem getCommunityInfo() {
		if (CommunityInfo == null) {
			return new CommunityItem();
		}
		return CommunityInfo;
	}

	public void setCommunityInfo(CommunityItem communityInfo) {
		CommunityInfo = communityInfo;
	}

	/**
	 * Constructor.
	 */
	public UserItem() {
	}

	public String getIntroduction() {
		return Introduction;
	}

	public void setIntroduction(String introduction) {
		this.Introduction = introduction;
	}

	/**
	 * Set the userId.
	 * 
	 * @param userid
	 *            userId
	 */
	public void setUserid(long userid) {
		this.Userid = userid;
	}

	/**
	 * Get the userId.
	 * 
	 * @return userId
	 */
	public long getUserid() {
		return this.Userid;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.Name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		if (Name == null || Name.length() == 0 && Phone != null
				&& Phone.length() >= 11) {
			Name = Phone.substring(0, Phone.length() - 7) + "****"
					+ Phone.substring(Phone.length() - 3);
		}
		if (Name == null || Name.length() == 0) {
			Name = Email;
		}
		return this.Name;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.Password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.Password;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.Email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.Email;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.Phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.Phone;
	}

	/**
	 * Set the houseNumber.
	 * 
	 * @param housenumber
	 *            houseNumber
	 */
	public void setHousenumber(String housenumber) {
		this.Housenumber = housenumber;
	}

	/**
	 * Get the houseNumber.
	 * 
	 * @return houseNumber
	 */
	public String getHousenumber() {
		return this.Housenumber;
	}

	/**
	 * Set the birthday.
	 * 
	 * @param birthday
	 *            birthday
	 */
	public void setBirthday(String birthday) {
		this.Birthday = birthday;
	}

	/**
	 * Get the birthday.
	 * 
	 * @return birthday
	 */
	public String getBirthday() {
		return this.Birthday;
	}

	/**
	 * Set the permission.
	 * 
	 * @param permission
	 *            permission
	 */
	public void setPermission(Integer permission) {
		this.Permission = permission;
	}

	/**
	 * Get the permission.
	 * 
	 * @return permission
	 */
	public int getPermission() {
		return this.Permission;
	}

	/**
	 * Set the background.
	 * 
	 * @param background
	 *            background
	 */
	public void setBackground(String background) {
		this.Background = background;
	}

	/**
	 * Get the background.
	 * 
	 * @return background
	 */
	public String getBackground() {
		return this.Background;
	}

	/**
	 * Set the avatar.
	 * 
	 * @param avatar
	 *            avatar
	 */
	public void setAvatar(String avatar) {
		this.Avatar = avatar;
	}

	/**
	 * Get the avatar.
	 * 
	 * @return avatar
	 */
	public String getAvatar() {
		return this.Avatar;
	}

	/**
	 * Set the friendMsg.
	 * 
	 * @param friendmsg
	 *            friendMsg
	 */
	public void setFriendmsg(Boolean friendmsg) {
		this.Friendmsg = friendmsg;
	}

	/**
	 * Get the friendMsg.
	 * 
	 * @return friendMsg
	 */
	public Boolean getFriendmsg() {
		return this.Friendmsg;
	}

	/**
	 * Set the businessMsg.
	 * 
	 * @param businessmsg
	 *            businessMsg
	 */
	public void setBusinessmsg(Boolean businessmsg) {
		this.Businessmsg = businessmsg;
	}

	/**
	 * Get the businessMsg.
	 * 
	 * @return businessMsg
	 */
	public Boolean getBusinessmsg() {
		return this.Businessmsg;
	}

	/**
	 * Set the activityMsg.
	 * 
	 * @param activitymsg
	 *            activityMsg
	 */
	public void setActivitymsg(Boolean activitymsg) {
		this.Activitymsg = activitymsg;
	}

	/**
	 * Get the activityMsg.
	 * 
	 * @return activityMsg
	 */
	public Boolean getActivitymsg() {
		return this.Activitymsg;
	}

	/**
	 * Set the time.
	 * 
	 * @param time
	 *            time
	 */
	public void setTime(String time) {
		this.Time = time;
	}

	/**
	 * Get the time.
	 * 
	 * @return time
	 */
	public String getTime() {
		return this.Time;
	}

	public boolean isFollowing() {
		return IsFollowing;
	}

	public void setFollowing(boolean isFollowing) {
		this.IsFollowing = isFollowing;
	}

	public void setFollowingCount(long followingCount) {
		this.FollowingCount = followingCount;
	}

	public long getFollowingCount() {
		return FollowingCount;
	}

	public void setFansCount(long fansCount) {
		this.FansCount = fansCount;
	}

	public long getFansCount() {
		return FansCount;
	}

	public void setServerCount(long serverCount) {
		this.ServerCount = serverCount;
	}

	public long getServerCount() {
		return ServerCount;
	}

	public void setFans(boolean isFans) {
		this.IsFans = isFans;
	}

	public boolean isFans() {
		return IsFans;
	}

	public void setLastActivity(String lastActivity) {
		this.LastActivity = lastActivity;
	}

	public String getLastActivity() {
		return LastActivity;
	}

}
