SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS ACTIVITY_SIGNUP;
DROP TABLE IF EXISTS COMMENT_APPROVAL;
DROP TABLE IF EXISTS COMMENT_OPPOSITION;
DROP TABLE IF EXISTS COMMUNITY;
DROP TABLE IF EXISTS FEEDBACK;
DROP TABLE IF EXISTS FRIEND;
DROP TABLE IF EXISTS INFORMATION;
DROP TABLE IF EXISTS INFORMATION_COMMENT;
DROP TABLE IF EXISTS INFORMATION_FOLLOWERS;
DROP TABLE IF EXISTS INFORMATION_REPORT;
DROP TABLE IF EXISTS INFORMATION_TAG;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_DYNAMIC;
DROP TABLE IF EXISTS USER_MESSAGE;
DROP TABLE IF EXISTS VERSION;




/* Create Tables */

CREATE TABLE ACTIVITY_SIGNUP
(
	-- 信息id
	INFORMATIONID BIGINT COMMENT '信息id',
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 名称
	NAME CHAR(32) COMMENT '名称',
	-- 电话
	PHONE CHAR(16) COMMENT '电话',
	-- 邮箱
	EMAIL CHAR(32) COMMENT '邮箱',
	-- 成人数量
	ADULTCOUNT INT COMMENT '成人数量',
	-- 小孩数量
	CHILDCOUNT INT COMMENT '小孩数量',
	-- 备注
	REMARK TEXT COMMENT '备注',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE COMMENT_APPROVAL
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 评论id
	COMMENTID BIGINT COMMENT '评论id',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE COMMENT_OPPOSITION
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 评论id
	COMMENTID BIGINT COMMENT '评论id',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE COMMUNITY
(
	-- 社区id
	COMMUNITYID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '社区id',
	-- 名称
	NAME CHAR(32) COMMENT '名称',
	-- 简介
	DESCRIPTION TEXT COMMENT '简介',
	-- 纬度
	LAT DOUBLE COMMENT '纬度',
	-- 经度
	LON DOUBLE COMMENT '经度',
	-- 图片
	IMAGE CHAR(64) COMMENT '图片',
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	PRIMARY KEY (COMMUNITYID)
);


CREATE TABLE FEEDBACK
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 内容
	CONTENT TEXT COMMENT '内容',
	-- 是否匿名
	ANONYMOUS BOOLEAN COMMENT '是否匿名',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE FRIEND
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 关注的用户id
	FRIENDID BIGINT COMMENT '关注的用户id',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE INFORMATION
(
	-- 信息id
	INFORMATIONID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '信息id',
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 标题
	TITLE CHAR(64) COMMENT '标题',
	-- 简介
	DESCRIPTION TEXT COMMENT '简介',
	-- 地址
	ADDRESS CHAR(64) COMMENT '地址',
	-- 经度
	LON DOUBLE COMMENT '经度',
	-- 纬度
	LAT DOUBLE COMMENT '纬度',
	-- 电话
	PHONE CHAR(16) COMMENT '电话',
	-- 图片
	IMAGE CHAR(64) COMMENT '图片',
	-- 语音
	VOICE CHAR(64) COMMENT '语音',
	-- 视频
	VIDEO CHAR(64) COMMENT '视频',
	-- 信息类型,1为活动,2为商家服务,3为个人服务
	INFOTYPE INT COMMENT '信息类型,1为活动,2为商家服务,3为个人服务',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	PRIMARY KEY (INFORMATIONID)
);


CREATE TABLE INFORMATION_COMMENT
(
	-- 评论id
	COMMENTID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '评论id',
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 信息id
	INFORMATIONID BIGINT COMMENT '信息id',
	-- 内容
	CONTENT TEXT COMMENT '内容',
	-- 分数(1-5分)
	SCORE FLOAT COMMENT '分数(1-5分)',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	PRIMARY KEY (COMMENTID)
);


CREATE TABLE INFORMATION_FOLLOWERS
(
	-- 信息id
	INFORMATIONID BIGINT COMMENT '信息id',
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE INFORMATION_REPORT
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 信息id
	INFORMATIONID BIGINT COMMENT '信息id',
	-- 内容
	CONTENT TEXT COMMENT '内容',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE INFORMATION_TAG
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 信息id
	INFORMATIONID BIGINT COMMENT '信息id',
	-- 标签id
	TAGID BIGINT COMMENT '标签id',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE PRODUCT
(
	-- 商品id
	PRODUCTID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '商品id',
	-- 信息id
	INFORMATIONID BIGINT COMMENT '信息id',
	-- 名称
	NAME CHAR(32) COMMENT '名称',
	-- 简介
	DESCRIPTION TEXT COMMENT '简介',
	-- 图片
	IMAGE CHAR(64) COMMENT '图片',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	PRIMARY KEY (PRODUCTID)
);


CREATE TABLE TAG
(
	-- 标签id
	TAGID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '标签id',
	-- 名称
	NAME CHAR(32) COMMENT '名称',
	-- 图标
	ICON VARCHAR(32) COMMENT '图标',
	PRIMARY KEY (TAGID)
);


CREATE TABLE USER
(
	-- 用户id
	USERID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '用户id',
	-- 名称
	NAME CHAR(32) COMMENT '名称',
	-- 密码
	PASSWORD CHAR(32) COMMENT '密码',
	-- 邮箱
	EMAIL CHAR(32) UNIQUE COMMENT '邮箱',
	-- 电话
	PHONE CHAR(16) COMMENT '电话',
	-- 楼号
	HOUSENUMBER CHAR(16) COMMENT '楼号',
	-- 出生日期
	BIRTHDAY CHAR(16) COMMENT '出生日期',
	-- 个人简介
	INTRODUCTION CHAR(64) COMMENT '个人简介',
	-- 权限,0为仅对关注对象开放,1为对小区认证用户开放,2为完全保密,3为公开
	PERMISSION INT COMMENT '权限,0为仅对关注对象开放,1为对小区认证用户开放,2为完全保密,3为公开',
	-- 个人主页,背景图片
	BACKGROUND CHAR(32) COMMENT '个人主页,背景图片',
	-- 头像
	AVATAR CHAR(64) COMMENT '头像',
	-- 是否开启朋友信息提醒
	FRIENDMSG BOOLEAN COMMENT '是否开启朋友信息提醒',
	-- 是否开启商家信息提醒
	BUSINESSMSG BOOLEAN COMMENT '是否开启商家信息提醒',
	-- 是否开启活动信息提醒
	ACTIVITYMSG BOOLEAN COMMENT '是否开启活动信息提醒',
	-- 社区id
	COMMUNITYID BIGINT COMMENT '社区id',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	PRIMARY KEY (USERID)
);


CREATE TABLE USER_DYNAMIC
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 目标id
	TARGETID BIGINT COMMENT '目标id',
	-- 1为关注活动,2为关注商家服务,3为关注个人服务,4为关注用户,5为评论,6为赞同评论,7为反对评论
	DYNAMICTYPE INT COMMENT '1为关注活动,2为关注商家服务,3为关注个人服务,4为关注用户,5为评论,6为赞同评论,7为反对评论',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE USER_MESSAGE
(
	-- 用户id
	USERID BIGINT COMMENT '用户id',
	-- 目标id
	TARGETID BIGINT COMMENT '目标id',
	-- 内容
	CONTENT TEXT COMMENT '内容',
	-- 图片
	IMAGE CHAR(64) COMMENT '图片',
	-- 语音
	VOICE CHAR(64) COMMENT '语音',
	-- 视频
	VIDEO CHAR(64) COMMENT '视频',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);


CREATE TABLE VERSION
(
	-- 社区id
	COMMUNITYID BIGINT COMMENT '社区id',
	-- 版本
	VERSIONCODE INT COMMENT '版本',
	-- 版本名字
	VERSIONNAME CHAR(8) COMMENT '版本名字',
	-- 下载地址
	DOWNLOAD CHAR(64) COMMENT '下载地址',
	-- 包名
	PACKAGENAME CHAR(64) COMMENT '包名',
	-- 二维码图片url
	QRCODEURL VARCHAR(64) COMMENT '二维码图片url',
	-- 发布时间
	TIME CHAR(32) COMMENT '发布时间',
	-- ID
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID',
	PRIMARY KEY (ID)
);



