package com.yuncommunity.item;

import java.io.Serializable;

/**
 * Model class of 活动报名.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActivitySignUpItem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** informationId. */
	private Long informationid;

	/** userId. */
	private Long userid;

	/** name. */
	private String name;

	/** phone. */
	private String phone;

	/** email. */
	private String email;

	/** adultcount. */
	private Integer adultcount;

	/** childcount. */
	private Integer childcount;

	/** remark. */
	private String remark;

	private String avatar;
	private String time;

	/**
	 * Constructor.
	 */
	public ActivitySignUpItem() {
	}

	/**
	 * Set the informationId.
	 * 
	 * @param informationid
	 *            informationId
	 */
	public void setInformationid(Long informationid) {
		this.informationid = informationid;
	}

	/**
	 * Get the informationId.
	 * 
	 * @return informationId
	 */
	public Long getInformationid() {
		return this.informationid;
	}

	/**
	 * Set the userId.
	 * 
	 * @param userid
	 *            userId
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * Get the userId.
	 * 
	 * @return userId
	 */
	public Long getUserid() {
		return this.userid;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the adultcount.
	 * 
	 * @param adultcount
	 *            adultcount
	 */
	public void setAdultcount(Integer adultcount) {
		this.adultcount = adultcount;
	}

	/**
	 * Get the adultcount.
	 * 
	 * @return adultcount
	 */
	public Integer getAdultcount() {
		return this.adultcount;
	}

	/**
	 * Set the childcount.
	 * 
	 * @param childcount
	 *            childcount
	 */
	public void setChildcount(Integer childcount) {
		this.childcount = childcount;
	}

	/**
	 * Get the childcount.
	 * 
	 * @return childcount
	 */
	public Integer getChildcount() {
		return this.childcount;
	}

	/**
	 * Set the remark.
	 * 
	 * @param remark
	 *            remark
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * Get the remark.
	 * 
	 * @return remark
	 */
	public String getRemark() {
		return this.remark;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getAvatar() {
		return null;
	}

}
