package com.yuncommunity.item;

import com.yuncommunity.base.BaseItem;

/**
 * Model class of product.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProductItem extends BaseItem {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** productId. */
	private Long Productid;

	/** informationId. */
	private Long Informationid;

	/** name. */
	private String Name;

	/** description. */
	private String Description;

	/** image. */
	private String Image;

	/** time. */
	private String Time;

	/**
	 * Constructor.
	 */
	public ProductItem() {
	}

	/**
	 * Set the productId.
	 * 
	 * @param productid
	 *            productId
	 */
	public void setProductid(Long productid) {
		this.Productid = productid;
	}

	/**
	 * Get the productId.
	 * 
	 * @return productId
	 */
	public Long getProductid() {
		return this.Productid;
	}

	/**
	 * Set the informationId.
	 * 
	 * @param informationid
	 *            informationId
	 */
	public void setInformationid(Long informationid) {
		this.Informationid = informationid;
	}

	/**
	 * Get the informationId.
	 * 
	 * @return informationId
	 */
	public Long getInformationid() {
		return this.Informationid;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.Name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.Name;
	}

	/**
	 * Set the description.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.Description = description;
	}

	/**
	 * Get the description.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.Description;
	}

	/**
	 * Set the image.
	 * 
	 * @param image
	 *            image
	 */
	public void setImage(String image) {
		this.Image = image;
	}

	/**
	 * Get the image.
	 * 
	 * @return image
	 */
	public String getImage() {
		return this.Image;
	}

	/**
	 * Set the time.
	 * 
	 * @param time
	 *            time
	 */
	public void setTime(String time) {
		this.Time = time;
	}

	/**
	 * Get the time.
	 * 
	 * @return time
	 */
	public String getTime() {
		return this.Time;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((Productid == null) ? 0 : Productid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProductItem other = (ProductItem) obj;
		if (Productid == null) {
			if (other.Productid != null) {
				return false;
			}
		} else if (!Productid.equals(other.Productid)) {
			return false;
		}
		return true;
	}

}
