package com.yuncommunity.theme.android.item;

import com.oldfeel.base.BaseItem;

/**
 * Model class of product.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProductItem extends BaseItem {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** productId. */
	private long Productid;

	/** informationId. */
	private long Informationid;

	/** name. */
	private String Name;

	/** description. */
	private String Description;

	/** image. */
	private String Image;

	/** time. */
	private String Time;

	/**
	 * Constructor.
	 */
	public ProductItem() {
	}

	/**
	 * Set the productId.
	 * 
	 * @param productid
	 *            productId
	 */
	public void setProductid(long productid) {
		this.Productid = productid;
	}

	/**
	 * Get the productId.
	 * 
	 * @return productId
	 */
	public long getProductid() {
		return this.Productid;
	}

	/**
	 * Set the informationId.
	 * 
	 * @param informationid
	 *            informationId
	 */
	public void setInformationid(long informationid) {
		this.Informationid = informationid;
	}

	/**
	 * Get the informationId.
	 * 
	 * @return informationId
	 */
	public long getInformationid() {
		return this.Informationid;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.Name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.Name;
	}

	/**
	 * Set the description.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.Description = description;
	}

	/**
	 * Get the description.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.Description;
	}

	/**
	 * Set the image.
	 * 
	 * @param image
	 *            image
	 */
	public void setImage(String image) {
		this.Image = image;
	}

	/**
	 * Get the image.
	 * 
	 * @return image
	 */
	public String getImage() {
		return this.Image;
	}

	/**
	 * Set the time.
	 * 
	 * @param time
	 *            time
	 */
	public void setTime(String time) {
		this.Time = time;
	}

	/**
	 * Get the time.
	 * 
	 * @return time
	 */
	public String getTime() {
		return this.Time;
	}

}
